server:
  port: 9005
spring:
  application:
    name: sy-gathering #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.190:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: souyue
  jpa:
    database: MySQL
    show-sql: true