server:
  port: 9010
spring:
  application:
    name: sy-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.190:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: souyue
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: itcast


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true