server:
  port: 9012
spring:
  application:
  name: sy‐web #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer‐ip‐address: true
zuul:
  routes:
    sy‐gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: sy‐gathering #指定Eureka注册中心中的服务id
    sy‐article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: sy‐article #指定Eureka注册中心中的服务id
    sy‐base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: sy‐base #指定Eureka注册中心中的服务id
    sy‐friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: sy‐friend #指定Eureka注册中心中的服务id
    sy‐qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: sy‐qa #指定Eureka注册中心中的服务id
    sy‐recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: sy‐recruit #指定Eureka注册中心中的服务id
    sy‐spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: sy‐spit #指定Eureka注册中心中的服务id
    sy‐user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: sy‐user #指定Eureka注册中心中的服务id
    sy‐search: #用户
      path: /search/** #配置请求URL的请求规则
      serviceId: sy‐search #指定Eureka注册中心中的服务id